# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fCWT <- function(x, fn = 100L, f0 = 0.001953125, f1 = 0.5, fs = 1, nthreads = 1L, optimize = FALSE, flags = "ESTIMATE", dist = "FCWT_LINFREQS", normalization = FALSE, bandwidth = 2.0) {
    .Call(`_RfCWT_fCWT`, x, fn, f0, f1, fs, nthreads, optimize, flags, dist, normalization, bandwidth)
}

