# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

start_profiler <- function(str) {
    .Call(`_RfCWT_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_RfCWT_stop_profiler`)
}

#' Executes a continous wavelet transform on an input signal
#'
#' @name fCWT
#' @param x Input signal
#' @param fn Number of Frequencies
#' @param f0 Low end of the frequency range
#' @param f1 High End of the frequency range
#' @param fs Sample rate of input signal
#' @param nthreads Number of threads to be used for openmp multithreading 
#' @param optimize Whether FFTW should attempt to create an optimized plan prior to starting 
#' @param dist Distribution of frequency bands across the range. Should be one of "FCWT_LINSCALES","FCWT_LOGSCALES", or "FCWT_LINFREQS"
#' @param normalization Whether or not the output scalogram should be normalized from range 0-1
#' @param bandwidth Frequency bandwidth of the mother wavelet to be used
#' @return List object with a complex matrix scalogram and the frequencies associated with each band
NULL

fCWT <- function(x, fn = 100L, f0 = 0.001953125, f1 = 0.5, fs = 1, nthreads = 1L, optimize = FALSE, flags = "FFTW_MEASURE", dist = "FCWT_LINFREQS", normalization = FALSE, bandwidth = 2.0) {
    .Call(`_RfCWT_fCWT`, x, fn, f0, f1, fs, nthreads, optimize, flags, dist, normalization, bandwidth)
}

