# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fCWT <- function(x, fn = 360, f0 = 0.001953125, f1 = 0.5, fs = 1, mother_wavelet = "MORLET", nthreads = 1L, optimisation_flags = "ESTIMATE", optimize = FALSE) {
    .Call(`_RfCWT_fCWT`, x, fn, f0, f1, fs, mother_wavelet, nthreads, optimisation_flags, optimize)
}

